server:
  port: 8081
spring:
#  application:
#    name: provider2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: -1
  scan:
    base-packages: com.fzk.springcloud  #服务暴露与发现消费所在的package
  cloud:
    subscribed-services: provider1